### ISSUE TITLE
Don't include build artefacts in source repo

### ISSUE THREAD

**Issue by topheman** [design-first/system-runtime#1]
`/build` folder shouldn't be included in the git source repo since the artefacts from the build pollute the diffs. Consider to:
- add `build` to `.gitignore` file
- keep this repo exclusively for sources
- include the `build` folder when you're publishing to npm (you might exclude the `src` folder in your `.npmignore`)
- consider using [npmcdn](https://npmcdn.com/) for bower users (transparent)

**Comment by ecarriou** [comment]
Thanks for the feedback.
In fact, I generate Runtime core system module in the build directory and this generated module is required by Runtime. It is helpful for me to have it managed by git.
But I take into account your remark and will update `.gitignore` file in a next release.

**Comment by ecarriou** [comment]
Fixed in the next release.
