### ISSUE TITLE
Error while installing a bundle

### ISSUE THREAD

**Issue by aprelle** [design-first/system-runtime#69]
Instructions were taken from here:
https://designfirst.io/systemruntime/documentation/docs/en/bundle-your-system.html

After the system was defined and saved into a file, I try to load it again using the command: 

runtime.install('mysystem.json');

Error: 
TypeError: $helper.getRuntime(...).system(...).id is not a function
... \node_modules\system-runtime\src\workflow.js:406
              .id()
  at action (... \node_modules\system-runtime\src\workflow.js:406:16)

**Comment by ecarriou** [comment]
Hi,

you get this error because:

- the name of your json file is not good or
- your json file is not in the same directory of your script.

I have updated the library so that you will now have a better error message. Example:

`runtime: error when calling the action 'install' on component 'runtime' (class '_Runtime'): Cannot find module '/Users/aaa/project/invalid.json'`

**Comment by aprelle** [comment]
Thanks for a quick response! The new version gives a better error message indeed:

runtime: error when calling the action 'install' on component 'runtime' (class '_Runtime'): Cannot find module 'undefined/MY_PATH_TO_JSON>'

It looks like "undefined/" is added somewhere on the way to the file path.

I found out that combination with fs.readFile may bring you to the positive result:

fs.readFile(MY_PATH_TO_JSON, 'utf8', (err, data) => {
    runtime.install(data);
    ...

**Comment by ecarriou** [comment]
I made some search about your issue and it appears that on Windows 10 the command `process.env.PWD` (that I use for installing a system) could return `undefined`. Are you on Windows 10 ?

I made a fix about this issue and I will deploy a new release with that fix very soon.

**Comment by ecarriou** [comment]
The library has been updated with the fix.

**Comment by aprelle** [comment]
I am on Windows 10. After the library update the model can be loaded successfully. 

Thanks for the quick help!

**Comment by ecarriou** [comment]
You are welcome. And thank you for having found this issue. 

I will close this bug as it seems that your problem is fixed now.

**Comment by aprelle** [comment]
Hi again, I am wondering, whether it would be possible to provide an absolute path instead of relative by calling runtime.install?

**Comment by ecarriou** [comment]
Yes, it is possible, I will check how to do that (i.e. if I use the same API or add a new one).
